name: GitHub Pages
on:
  push:
    branches:
      - "main"

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build
        run: |
          wasm-pack build --target web
          cp src/assets/* pkg

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: pkg

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
